name: CI/CD Pipeline

on:
  push:
    branches:
      - feature1
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Build project
        run: |
          echo "Building the project..."
          # Add your build commands here (e.g., mvn package or gradle build)

      - name: Run tests
        run: |
          echo "Running tests..."
          # Add your test commands here

      - name: Deployment
        run: |
          echo "Deploying the application..."
          # Add deployment scripts or AWS/Jenkins trigger commands here
